version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FIREBASE_CREDENTIALS_PATH=/app/startup-cf3fd-firebase-adminsdk-fbsvc-893409a921.json
      # Uncomment and set this if testing the environment variable method
      # - FIREBASE_CREDENTIALS_JSON="{your_firebase_credentials_json_here}"
    volumes:
      - ./:/app 